### PR TITLE
Fixed a dupe bug that occurred when unloading an armor stand while its inventory GUI was open

### PR DESCRIPTION
**Pull request by TheNikLev**
Showcase: [yt link](https://youtu.be/-jbHfjZ7na4?si=hat0P5OnhZ3S4qBd)

### CODE REVIEW

**Comment by TheNikLev** [comment]
Hey! If this one is accepted, should I create another merge request for 1.20?

**Comment by Patbox** [comment]
I would also suggest closing the ui if that happens! And don't worry, I can merge it up

**Comment by TheNikLev** [comment]
Okay, thank you

**Comment by TheNikLev** [comment]
Oh, sorry, I accidentally closed it, just noticed
About closig the ui, I wasn't sure how to do it because I haven't managed to find something like `onTick()` for SimpleGui,  similar to what there is in BaseGui

**Comment by TheNikLev** [comment]
Ah, I guess I understood what you wanted

**Pull request merged**
